### ISSUE TITLE
Implement v-clamp with v-html

### ISSUE THREAD

**Issue by ChunAllen** [Justineo/vue-clamp#14] opened 2019-06-11 07:53 UTC
I'm currently using Vuetify and Vue-Clamp 
The `body` contains html elements such as `span`, `<b></b>`, `<p></p> etc...`

I tried 
```
<div class="caption mb-3">
    <v-clamp autoresize :max-lines="10" v-html="body"></v-clamp>
</div>
```
and
```
<v-clamp autoresize :max-lines="10">
   <div class="caption mb-3" v-html="body"></body>
</v-clamp>
```
But both approach doesn't work

**Comment by Justineo** [comment] 2019-06-11 08:52
Duplicate of #13

**Closed by Justineo** 2019-06-11 08:52 UTC

**Comment by brmdbr** [comment] 2020-10-12 09:10
@ChunAllen Have you found a solution for this? Running into the same problem.

**Comment by drayanaindra** [comment] 2020-11-28 14:38
Hi, i also have same issue. Any suggestion to solve this issue?
